### ISSUE TITLE
How to use proxy request?

### ISSUE THREAD

**Issue by huasio** [UnAfraid/SpringTelegramBot#1]
Telegram cannot be accessed in China, so how to use a proxy in the project to get access to the telegram address?

### I use this method, it is unable to pass the proxy, it will give me a timeout error.
![image](https://user-images.githubusercontent.com/23445537/139386855-1753d98d-b0a7-4551-b48d-b71ece583199.png)

![image](https://user-images.githubusercontent.com/23445537/139386833-534a1405-14da-46cc-b19e-cb9fce2effa5.png)
![image](https://user-images.githubusercontent.com/23445537/139387083-1362098a-7ba6-47eb-aa98-23835e574528.png)

### Here is my proxy server address.
![image](https://user-images.githubusercontent.com/23445537/139387322-29c09fd5-4d6c-4652-88a6-e5f3ceb741c7.png)

**Comment by UnAfraid** [comment]
Hi,

Thanks for the issue, i've created a pull request https://github.com/UnAfraid/SpringTelegramBot/pull/2 with proxy support, can you please give it a try?

Add your proxy configuration in com.github.unafraid.spring.config.DefaultBotOptionsConfig

**Comment by huasio** [comment]
> Hi,
> 
> Thanks for the issue, i've created a pull request #2 with proxy support, can you please give it a try?
> 
> Add your proxy configuration in com.github.unafraid.spring.config.DefaultBotOptionsConfig

Thanks, I have completed my agency work.

**Comment by UnAfraid** [comment]
> > Hi,
> > Thanks for the issue, i've created a pull request #2 with proxy support, can you please give it a try?
> > Add your proxy configuration in com.github.unafraid.spring.config.DefaultBotOptionsConfig
> 
> Thanks, I have completed my agency work.

Did you had the chance to try #2 out?
